### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by gtrogers** [alphagov/backdrop-ga-collector#8]
Hey guys,

Looking at picking up a new story on this and realised I've either forgotten or never knew how it was supposed to work. Readme would be useful for this kind of problem.

Thanks.

**Comment by pwaller** [comment]
Is this not solved? [There exists a readme which looks useful enough](https://github.com/alphagov/backdrop-ga-collector/blob/master/README.md).

**Comment by robyoung** [comment]
@pwaller that's a really good point, we don't make issues anywhere near visible enough.
@gtrogers I'm going to close this as we seem to have a useful README. Give us a shout if it's not helpful enough. Give us a shout anyway, it would be good to catch up!
